### ISSUE TITLE
Analysis too slow when contains inline equations

### ISSUE THREAD

**Issue by DaisukeUra** [fgborges/textlint-plugin-latex2e#16]
$$による数式が複数含まれていると，ファイルの分析がとても遅くなります．

`time textlint main.tex` を実行

---

```latex
ここで $\theta_d$ は目標角度， $\theta_i$ は $i$ 番目の振り子の角度， $\Delta \tau$ は印加トルクを表すものとする．
```
結果：        2.67 real         3.11 user         0.47 sys

---

```latex
ここで $\theta $ は目標角度， $\theta $ は $i$ 番目の振り子の角度， $\Delta \tau$ は印加トルクを表すものとする．
ここで $\theta $ は目標角度， $\theta $ は $i$ 番目の振り子の角度， $\Delta \tau$ は印加トルクを表すものとする．
ここで $\theta $ は目標角度， $\theta $ は $i$ 番目の振り子の角度， $\Delta \tau$ は印加トルクを表すものとする．
ここで $\theta $ は目標角度， $\theta $ は $i$ 番目の振り子の角度， $\Delta \tau$ は印加トルクを表すものとする．
ここで $\theta $ は目標角度， $\theta $ は $i$ 番目の振り子の角度， $\Delta \tau$ は印加トルクを表すものとする．
```
結果：      132.88 real       132.95 user         2.82 sys

---

OSはosx 10.14.6， homebrew経由で textlint v11.3.1 をインストールしており，こちらのreadme通りにプラグインをインストールしています．

.textlintrc は以下のとおりです．

```
{
    "rules": {
        "preset-ja-technical-writing": true,
    },
    plugins: ["latex2e"]
}
```

**Comment by fgborges** [comment]
返事が遅くなりすみません。これは、`$$ ... $$`と`$ ... $`を区別するために、パーサーで否定先読みを実行していることに起因すると考えられます。もっとも簡単な解決策としては、`\( ... \)`や`\[ ... \]`を使ってもらうと、速度が遅くなることを防げます。

そもそも$記号を使った数式表現はLaTeXの文法ではなくTeXの文法であるため、他のchktexなどでも警告がでるものですので、そちらへの移行をお勧めします。

さて問題に戻りますが、JavaScriptの正規表現のエンジンの特性に依存するところですので、考えられる方法としては、正規表現を使わないやり方を考える必要がありそうですね。調査してみます。

**Comment by fgborges** [comment]
ひとまず、$記号を使った解析を高速化するために正規表現`\$[^$]+\$`を使うようにしました。これは`$a+\$+b$`は解析できなくなりましたが、しかし必要十分であると判断しました。もし、問題があるようでしたら、再びIssueを開いてください。

**Comment by kn1cht** [comment]
@fgborges いつも開発ありがとうございます。こちらのissueは、npmに公開されている"v0.3.0"では解消されていますか？

v0.3.0で数式入りのファイルを処理したところ終了せず、GitHubから直接installしたら問題が解消しました。

**Comment by fgborges** [comment]
うっかりしていました。たった今、更新分をv0.3.1として公開しました。よろしくおねがいします。

**Comment by kn1cht** [comment]
迅速なご対応ありがとうございます 🙌
