### ISSUE TITLE
`verbatim` environment is not supported

### ISSUE THREAD

**Issue by pddg** [fgborges/textlint-plugin-latex2e#23]
## 環境

- macOS 10.15.2
- textlint 11.5.0
- textlint-plugin-latex2e 0.3.0

## 発生した現象

\verbはサポートされていますが，`\begin{verbatim} ~ \end{verbatim}`がサポートされていませんでした．

```
✖ Stack trace
Error: 
-- PARSING FAILED --------------------------------------------------

  75 | \begin{verbatim}
  76 |     $ make watch target=sections/usage
> 77 | \end{verbatim}
     | ^
  78 | 

Expected one of the following: 

'$$', '\(', '\[', '{', /%([^\n\r]*)/, /\$(?!\$)/, /\\(?!begin|end|verb|i+tem)([a-zA-Z_@]+|[`'^"~=_@#$%&{},\.\/\\ ])/, /\\(verb*?)/, \begin{.*?}, \begin{document}, \begin{itemize|enumerate|description}, newline, none of '$%{}\

'
```

\verbと同じく，文字列をそのまま出力する構文のため，コードブロックとして扱って頂くのが良いかも知れません．

**Comment by fgborges** [comment]
報告ありがとうございます。確かにBugですね。恐らくitemizeのようにEnvironmentのパーサーを個別に設定する必要がありそうです。現在、ちょっと忙しく27日以降なら私の方でパーサーを拡張できます。マージ作業とコードレビューは可能ですのでお急ぎでしたらいつでもプルリクエストを下さい。
